linux_docker_builder:    
  env:
    DOCKERHUB_USER: ENCRYPTED[d141f69cf141cb769cc02c110baa2cfb6e316535dfa7d24f0a93ae00629c386e7f77286660adec8887823aa409447cd1]
    DOCKERHUB_PASS: ENCRYPTED[fee383dcad0a81ec7278117c45f69366870903264bccd71e9880224e189cff271bd82dc154f711917478a1492060753b]
  script: |
    export TAG=${CIRRUS_TAG:-latest}-amd64
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} . -f Dockerfile
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}

linuxarmv7_docker_builder:    
  env:
    DOCKERHUB_USER: ENCRYPTED[d141f69cf141cb769cc02c110baa2cfb6e316535dfa7d24f0a93ae00629c386e7f77286660adec8887823aa409447cd1]
    DOCKERHUB_PASS: ENCRYPTED[fee383dcad0a81ec7278117c45f69366870903264bccd71e9880224e189cff271bd82dc154f711917478a1492060753b]
  script: |
    export TAG=${CIRRUS_TAG:-latest}-armv7
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} . -f Dockerfile.rpi --build-arg ARCH=armv7l --build-arg CROSSCOMPILER=https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%2010.2.0/Raspberry%20Pi%202%2C%203/cross-gcc-10.2.0-pi_2-3.tar.gz --build-arg IMAGE=balenalib/raspberry-pi2
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}

linuxarmv6_docker_builder:    
  env:
    DOCKERHUB_USER: ENCRYPTED[d141f69cf141cb769cc02c110baa2cfb6e316535dfa7d24f0a93ae00629c386e7f77286660adec8887823aa409447cd1]
    DOCKERHUB_PASS: ENCRYPTED[fee383dcad0a81ec7278117c45f69366870903264bccd71e9880224e189cff271bd82dc154f711917478a1492060753b]
  script: |
    export TAG=${CIRRUS_TAG:-latest}-armv6
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} . -f Dockerfile.rpi --build-arg CROSSCOMPILER=https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%2010.2.0/Raspberry%20Pi%201%2C%20Zero/cross-gcc-10.2.0-pi_0-1.tar.gz
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG} 

publish_docker_builder:
  depends_on: 
    - linuxarmv6
    - linuxarmv7
    - linux
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKERHUB_USER: ENCRYPTED[d141f69cf141cb769cc02c110baa2cfb6e316535dfa7d24f0a93ae00629c386e7f77286660adec8887823aa409447cd1]
    DOCKERHUB_PASS: ENCRYPTED[fee383dcad0a81ec7278117c45f69366870903264bccd71e9880224e189cff271bd82dc154f711917478a1492060753b]
  script: | 
    docker info
    export TAG=${CIRRUS_TAG:-latest}
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker manifest create --amend $CIRRUS_REPO_FULL_NAME:${TAG} $CIRRUS_REPO_FULL_NAME:${TAG}-amd64 $CIRRUS_REPO_FULL_NAME:${TAG}-armv7 $CIRRUS_REPO_FULL_NAME:${TAG}-armv6
    docker manifest annotate $CIRRUS_REPO_FULL_NAME:${TAG} $CIRRUS_REPO_FULL_NAME:${TAG}-armv7 --os linux --arch arm --variant v7
    docker manifest annotate $CIRRUS_REPO_FULL_NAME:${TAG} $CIRRUS_REPO_FULL_NAME:${TAG}-armv6 --os linux --arch arm --variant v6l
    docker manifest push $CIRRUS_REPO_FULL_NAME:${TAG} -p
