name: Build docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
      
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow --tags

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
            
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      id: setup
      uses: docker/setup-buildx-action@v3

    - name: Build and push devcontainer
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        target: builder
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}-dev 

    - name: Build and push
      uses: docker/build-push-action@v6
      id: push
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }} 
        platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6

    - name: Attest
      uses: actions/attest-build-provenance@v1
      with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

